###
GET http://localhost:3000/api/contactos

###
GET http://localhost:3000/api/contactos?page=1&size=3

###
GET http://localhost:3000/api/contactos?page=0&size=3&contacto=aca

###
POST http://localhost:3000/api/contactos
Content-Type: application/json

{
    "contacto" : "Asamblea General Universitaria",
    "telefono" : "2511-2022",
    "extension" : "2022, 3023",
    "correo" : "ejemplo@ues.edu.sv"
}

###
GET http://localhost:3000/api/contactos/63446628fe93624ef4494735

###
DELETE  http://localhost:3000/api/contactos/6386b4cb4c5ddda72ac01b41

###
//GET  http://localhost:3000/api/contactos/done

###
PUT http://localhost:3000/api/contactos/63446479fe93624ef44946f7
Content-Type: application/json

{
    "extension" : "2008"
}