GET http://localhost:3000/api/tasks
###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Trabajar en el proyecto de javascript",
    "description": "Trabajo de universidad",
    "done": "true"
}

###
GET http://localhost:3000/api/tasks/633cc2ebcb7791e57dc8f77b

###
DELETE  http://localhost:3000/api/tasks/633cc5ebb688e292d48bf905

###
GET  http://localhost:3000/api/tasks/done

###
PUT http://localhost:3000/api/tasks/633cc2ebcb7791e57dc8f77b
Content-Type: application/json

{
    "title": "Crear un sitio web en wordpress"
}